# Generated by Django 4.0.1 on 2022-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trusted_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partner_name', models.CharField(max_length=100)),
                ('Partner_logo', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Trusted_Partner',
                'verbose_name_plural': 'Trusted_Partners',
            },
        ),
    ]
