# Generated by Django 4.0.1 on 2022-01-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=70)),
                ('shoe_desc', models.CharField(max_length=250)),
                ('shoe_num', models.IntegerField()),
                ('shoe_type', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('shoe_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.trusted_partner')),
            ],
            options={
                'verbose_name': 'shoe',
                'verbose_name_plural': 'shoes',
            },
        ),
    ]
