# Generated by Django 4.0.1 on 2022-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoe_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
