# Generated by Django 4.0.1 on 2022-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoe_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoe_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
